### PR TITLE
Docs installation

### PR DESCRIPTION
**Pull request by caspervdw**
This adds some changes corresponding to the `conda-forge` migration. Also, I added a short intro on git in order to help potential contributors over the first few hurdles.

### CODE REVIEW

**Comment by caspervdw** [comment]
Are you OK bumping the numpy tests for the py2.7 tests to 1.9.x ? Pyfftw is not available on conda-forge with an earlier numpy version.

**Comment by caspervdw** [comment]
Instead I dropped pyfftw from the legacy tests.

**Comment by nkeim** [comment]
This is great! I hadn't realized that some of our docs were so out-of-date. This looks ready for merge. You might want to also link to this wiki page: https://github.com/soft-matter/trackpy/wiki/Information-for-contributors . 

I suspect there are very few people using pyfftw with trackpy v0.3. So I agree that it can be sacrificed in the tests.

**Comment by caspervdw** [comment]
A colleague gave me the heads-up. I added the link to the wiki! This can be merged.

**Comment by caspervdw** [comment]
Shall I backport the installation page to the current version docs?

**Comment by caspervdw** [comment]
FYI I backported the installation notes to v0.3.2 http://soft-matter.github.io/trackpy/v0.3.2/installation.html

**Comment by nkeim** [comment]
Thanks!!


On Feb 11, 2017, 9:05 AM -0800, Casper van der Wel <notifications@github.com>, wrote:

FYI I backported the installation notes to v0.3.2 http://soft-matter.github.io/trackpy/v0.3.2/installation.html

**Pull request merged**
