### PR TITLE
BLD: Add numba to py35 build.

### LINKED ISSUE #289: Python 3.5 and numba
We might as well do whatever we need to do to make v0.3.0 compatible with Python 3.5, but I was surprised to find that numba is not ready for 3.5 yet:

```
Hint: the following packages conflict with each other:
  - numba
  - python 3.5*
```

### PR DESCRIPTION
**Pull request by danielballan**
Closes #289

### CODE REVIEW

**Comment by danielballan** [comment]
Sweet! The latest numba passes the tests.

**Comment by caspervdw** [comment]
Nice! This needs a rebase

**Comment by caspervdw** [comment]
And why fix pandas to 0.17? It is the latest version

**Comment by nkeim** [comment]
Good point. I wouldn't object to this PR removing the version spec. It's just that sometimes conda surprises you, so I didn't want to take any chances.

**Comment by danielballan** [comment]
It's good that we ran Travis with specifically 0.17 at least once, given
the reported bug. I agree relaxing going forward is good, for the "latest"
build.

I made that changed and rebased. If Travis is happy, this is ready.

**Pull request merged**
