### PR TITLE
CLN Address the many warning messages in the tests

### PR DESCRIPTION
**Pull request by caspervdw**
I cleaned the many warning messages that were triggered during the tests.

Biggest change is that I impelemented `StrictTestCase` that makes pandas and numpy strict, and suppresses trackpy log messages. All tests are rebased on this TestCase (hence the many changed files)

The commit messages are clear, most of it is rather straightforward.

### CODE REVIEW

**Comment by caspervdw** [comment]
Can this be merged? Before it needs a potentially messy rebase... There are no API changes, only edits to suppress warning messages and superfluous logging during tests.

**Comment by caspervdw** [comment]
I have rebased this PR. @nkeim @danielballan @tacaswell sorry for pushing this but it should go in soon as it touches many parts (no API breaks, only cleaning)

**Comment by nkeim** [comment]
I am encountering 2 failed tests when I run this locally, tests that do not fail for the master branch. Below is the output from `py.test`:

```python
F
self = <trackpy.tests.test_static.TestArcLenAndArea testMethod=test_symmetry_circle_corner>

    def test_symmetry_circle_corner(self):
        h0 = np.random.random(self.N)
        h1 = np.random.random(self.N) * np.sqrt(1-h0**2)
        R = np.random.random(self.N) * 100
>       assert_almost_equal(circle_corner_arclen(h0, h1, R),
                            circle_corner_arclen(h1, h0, R))

test_static.py:250: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

h1 = array([ 0.13213561,  0.92991536,  0.63645175,  0.27223901,  0.08234053,
        0.57355285,  0.90063202,  0.35987159,  0.77979641,  0.11142248])
h2 = array([ 0.0730626 ,  0.11344195,  0.45705239,  0.57569329,  0.93348943,
        0.55155392,  0.32727611,  0.37965461,  0.46330759,  0.9627463 ])
r = array([ 38.24715853,  23.85879811,  64.15581671,  24.61170601,
         0.85620529,  93.41073262,  24.7740559 ,  24.64852188,
        44.96048247,  14.03539066])

    def circle_corner_arclen(h1, h2, r):
        """ Length of a circle arc of circle with radius R that is bounded by
        two perpendicular straight lines `h1` and `h2` from the origin.
        h1**2 + h2**2 < R**2
        h1 >= R
        h2 >= R
        """
>       return r*(np.arccos(h2 / r) - np.arcsin(h1 / r))
E       FloatingPointError: invalid value encountered in arccos

../static.py:268: FloatingPointError

F
self = <trackpy.tests.test_static.TestArcLenAndArea testMethod=test_symmetry_sphere_corner>

    def test_symmetry_sphere_corner(self):
        h0 = np.random.random(self.N)
        h1 = np.random.random(self.N) * np.sqrt(1-h0**2)
        h2 = np.random.random(self.N) * np.sqrt(1-h0**2-h1**2)
        R = np.random.random(self.N) * 100
>       result = np.array([sphere_corner_area(h0, h1, h2, R),
                           sphere_corner_area(h1, h2, h0, R),
                           sphere_corner_area(h2, h0, h1, R),
                           sphere_corner_area(h2, h1, h0, R),
                           sphere_corner_area(h0, h2, h1, R),
                           sphere_corner_area(h1, h0, h2, R)])

test_static.py:265: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

x = array([ 0.15239859,  0.73142131,  0.18138587,  0.02768484,  0.89071772,
        0.18465066,  0.20770432,  0.8596566 ,  0.85542148,  0.91298934])
y = array([ 0.75089414,  0.23785579,  0.09779331,  0.55687134,  0.07920176,
        0.1224299 ,  0.40284464,  0.50541872,  0.02913091,  0.1715768 ])
z = array([  6.26799357e-01,   1.31554626e-03,   9.49432151e-01,
         7.65971009e-01,   3.14072831e-01,   6.57207283e-01,
         7.86359205e-01,   4.65361312e-02,   3.90256052e-01,
         3.86441125e-04])
r = array([ 89.74922526,  93.06194387,  35.01313169,  34.33278894,
        58.51835189,  48.87377809,  47.86157351,   0.12180845,
        35.08723155,   8.66792672])

    def sphere_corner_area(x, y, z, r):
        """ Area of a sphere 'corner' of sphere with radius R that is bounded by
        three perpendicular flat planes `h0`, `h1`, `h2` from the origin. """
>       pxy = np.sqrt(r**2 - x**2 - y**2)
E       FloatingPointError: invalid value encountered in sqrt

../static.py:289: FloatingPointError
```

Output of `diag.dependencies()`:

```python
OrderedDict([('six', '1.10.0'),
             ('numpy', '1.10.4'),
             ('scipy', '0.17.0'),
             ('matplotlib', '1.5.1'),
             ('pandas', '0.17.1'),
             ('scikit-image', None),
             ('pyyaml', None),
             ('pytables', None),
             ('numba', '0.23.1'),
             ('pyfftw', None),
             ('python', '3.5.1')])
```

**Comment by nkeim** [comment]
Ah! I see now that this is because of `np.seterr('raise')`. We need to adjust the range of the random numbers.

**Comment by caspervdw** [comment]
Thanks for checking! Do you think leaving `np.seterr('raise')` is a good idea? I am not sure, it could cause a headache later. At the other hand, it could save us one too..

**Comment by nkeim** [comment]
It looks like we can call `np.seterr('ignore')` in these two tests, and the next tests that will run will set it back to `'raise'`. Is that right?

This is probably just a quirk in the macOS stdlib.

**Comment by caspervdw** [comment]
Actually it was a real mistake in these tests :) there was a small chance on a square root of a negative number. That should be solved now.

**Comment by nkeim** [comment]
Fascinating! It looks like this is a hack to work around the limits of numerical precision. I wonder why it failed consistently on my computer — maybe something is setting the random seed for me? Mentioning @dwieker since I think that was his formulation.

With that, merging. Thanks!

**Pull request merged**
