### PR TITLE
Backport docs to 0.3.0

### PR DESCRIPTION
**Pull request by caspervdw**

### CODE REVIEW

**Comment by danielballan** [comment]
Merging in spite of broken build because that has nothing to do with this PR

**Comment by caspervdw** [comment]
Could you build and push the backported docs?

**Comment by danielballan** [comment]
I haven't forgotten this. I want Travis to auto-push to /dev whenever we merge commits to master. I might as well also set up Travis to auto-push to /0.3.0 whenever we merge commits to the 0.3.0-doc branch. I will try to get to this soon. Or feel free to give it a try if you feel inspired.

**Comment by caspervdw** [comment]
Do you have examples that include docbuilding? At first sight? I am afraid that it would mean to include the login password in publicly accessible files.

**Comment by caspervdw** [comment]
That question mark should have been a comma..

**Comment by tacaswell** [comment]
See https://github.com/matplotlib/matplotlib/blob/master/.travis.yml#L130  travis has a way to encrypt oauth tokens into ENVS (you encrypt the value with the public half of a key they hold).

**Comment by caspervdw** [comment]
That is neat! I don't see myself implementing this in the next weeks, have to focus on my work, but if you dont have time I can have a look after Christmas

**Comment by tacaswell** [comment]
https://docs.travis-ci.com/user/environment-variables/#Encrypted-Variables for reference.

**Pull request merged**
