### PR TITLE
Doc cleanup

### PR DESCRIPTION
**Pull request by caspervdw**
I looked at the automatically generated docs, and removed the tests. Also I simplified the doc build (don't run tests, they are covered already in GH Actions) and pinned the versions for future stability.

### CODE REVIEW

**Comment by caspervdw** [comment]
Also fixes #659 partially.

**Comment by caspervdw** [comment]
This will be the last PR before 0.5.0! Please tell me if there is anything else worth doing before releasing 0.5.0 @nkeim @rbnvrw

**Comment by nkeim** [comment]
Excellent, thanks! Assuming Travis CI is OK with the new file, I am 👍 on proceeding with v0.5rc1. Let me know if you'd like some help. Trackpy has not had a release since I updated the instructions on the wiki, so I hope they are useful.

**Comment by caspervdw** [comment]
I needed two attempts. The first one failed because of the .md -> .rst conversion didn't work anymore. Luckily, pypi now understands .md natively. I commited a small fix directly to master to use that.  v0.5.0rc2 is now on PyPI and a PR is building on conda-forge. https://github.com/conda-forge/trackpy-feedstock/pull/19  

Please try it out.  If everything checks out, the actual release can be done next week or so.

**Comment by caspervdw** [comment]
Done! Just waiting for the autotick-bot at conda-forge (I can't get the rerendering to work locally)

**Pull request merged**
