### PR TITLE
ENH: Standard deviation calculation for emsd()

### PR DESCRIPTION
**Pull request by vivarose**
This adds the ability to calculate the standard deviation when calculating the ensemble mean square displacement with tp.motion.emsd(), as discussed at https://github.com/soft-matter/trackpy/issues/349

### CODE REVIEW

**Comment by caspervdw** [comment]
Thanks @vivarose!  The code looks fine to me. The Travis fail is another issue that is not connected with this PR.

Just to be concise on a theoretical ground, do you want to show the standard deviation of the samples, or the standard deviation in the average of the samples? The code suggest the latter, but I am not completely sure if the approach is mathematically correct.

Do you have a reference to put in the Notes section of the emsd?

**Comment by vivarose** [comment]
Hi @caspervdw, it is the standard deviation in the mean of the samples. 

I know it is possible to calculate the std for a single particle msd, but I have not familiarized myself with that yet. So this is the std of the mean over the single particle msds. 

And it's biased (without Bessel's correction). It would be straightforward to include Bessel's correction but the std would still be biased.

I have a notebook where I used the new emsd() function here: https://github.com/vivarose/using_trackpy/blob/master/MSD_standard_deviation.ipynb

I can get back to you about references.

**Comment by caspervdw** [comment]
Thanks for the clarification. I think we have to get to the bottom of the theoretic part on this before we can merge this. I am afraid that by averaging the squared deviations of the msds, which are already averages, we underestimate the error. I hope some reference can clear that up.

In either case, the Bessel correction is only a minor one as we are talking about N >> 1.

**Comment by tdimiduk** [comment]
I think there may be a Travis glitch on python 3.5, I grabbed @vivarose's code and it runs fine under anaconda python 3.5 on my local box.

**Comment by vivarose** [comment]
I think the test failed because the new version of pandas, 0.18.0, is causing an error. I ran into this problem today when I updated pandas.

**Comment by danielballan** [comment]
Hmm. The proximate cause is `np.round`, but that API has not changed.

```python
assert_series_equal(np.round(actual), expected)
  File "/home/travis/mc/envs/testenv/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 2786, in round_
    return round(decimals, out)
TypeError: round() takes from 1 to 2 positional arguments but 3 were given
```

Maybe something funny about how the Series objects `actual` and `expected` are being interpreted as arrays?

**Comment by vivarose** [comment]
I think the soft-matter/master would also fail this travis build with Pandas 0.18.0.

**Comment by danielballan** [comment]
@vivarose Definitely -- I agree these failures are unrelated to your PR. I'm just speculating about what could have changed in pandas....

**Comment by danielballan** [comment]
I read the pandas release notes and nothing jumps out. I'll run these with `--pdb` tomorrow and try to learn more.

**Comment by vivarose** [comment]
I have now integrated the ability to calculate the standard deviation when calculating the ensemble msd (emsd). 

Previously, I was pretending that each individual particle msd (imsd) has no error and calculating the standard deviation using frequency weights based on the N column, and @caspervdw was concerned that this would underestimate the standard deviation.

Now, in a separate branch (not yet pull-requested here), I have a new approach. I am calculating the imsd standard errors using the Flyvbjerg and Petersen approach, implemented by [pyblock](https://pypi.python.org/pypi/pyblock) and/or https://github.com/manoharan-lab/flyvbjerg-std-err. Then I can use the imsd stderr to calculate the emsd standard deviation, by using the inverse square of the imsd stderrs as reliability weights. 

I believe that by incorporating the imsd stderr in this way, we are obtaining a better estimate of the std of the emsd.

My branch for calculating the standard deviation is here:
https://github.com/vivarose/trackpy/tree/using_fp_stderr

I have only just arrived at this point so I'm not quite ready to pull-request it. In addition to testing it out a bit, there are a few more things I would like to do:
1) Learn more about _msd_fft() to see if I can calculate the fp_stderr in that function. Right now I can only do it in the _msd_gaps() function.
2) Make it more user-friendly to plot the imsd with error bars. (I have a way of doing it but it's not built-in yet.)

This does not account for errors in the tracking. Those errors are known to increase the msd, especially at small displacements.

**Comment by Jmlannan** [comment]
Hello, sorry to post on such an old issue, but could the walkthrough be updated to show this functionality?
I believe it should looks something like this with the current version:

`
mpp = 100 #microns per pixel
fps =24
detailed_emsd = tp.emsd(t1, mpp, fps, detail=True)
fig, ax = plt.subplots()
ax.set_xscale('log')
ax.set_yscale('log')
ax.set(ylabel=r'$\langle \Delta r^2 \rangle$ [$\mu$m$^2$]', xlabel='lag time $t$')
plt.errorbar(detailed_emsd["lagt"].to_numpy(), 
    detailed_emsd["msd"].to_numpy(), 
     yerr = detailed_emsd["<y^2>"].to_numpy() + detailed_emsd["<x^2>"].to_numpy(), 
     )
plt.show() `

biased on: https://github.com/vivarose/using_trackpy/blob/master/MSD_standard_deviation.ipynb

**Comment by vivarose** [comment]
@Jmlannan, no, that is not the correct errorbar. The official version of soft-matter/trackpy doesn't calculate the error. The "<y^2>" and "<x^2>" columns are not uncertainty, they are mean square displacement in y and x, respectively.

You are welcome to use my code, https://github.com/horowitz-lab/using_trackpy/blob/master/stdev_emsd.py, to calculate the standard deviation.

**Comment by nkeim** [comment]
@vivarose Am I right that you or I could rebase this and it would be a viable PR? From this discussion and the one in #349 it was unclear whether you still recommend this code for general use.

**Pull request closed without merging**
