### PR TITLE
PERF: Support for numba 0.16+

### PR DESCRIPTION
**Pull request by nkeim**
Due to a refactoring of the numba backend starting with 0.16 (they are now on 0.17), the numba feature-finding code could no longer be compiled to LLVM; instead it was running slower than pure Python. To fix it, I had to remove all array allocation from the function. The result should now run even faster than before, with all compatible versions of numba.

### CODE REVIEW

**Comment by danielballan** [comment]
Thanks for doing this.

I think we should put `nopython=True` into the codebase and drop support for older versions of numba. I just can't imagine how this could realistically hurt our users, and it's a useful assurance that our numba code will stay fast.

**Comment by nkeim** [comment]
That's a valid position. It just seems so weird; we'd lose compatibility with a version of numba released just one year ago. But I guess the time to do it is at v0.3; it offers a lot of improvements in exchange for some potential inconvenience.

To restore `nopython=True`, I think we'd want to 

- require numba 0.13 or later
- recommend 0.17 in the docs
- Tell Travis to test on 0.13 and the latest version

I actually have no idea how to do the first one — I can't even find `meta.yaml` (is it in the repo?).

Would anyone else care to chime in on an appropriate life-cycle for dependencies?

**Comment by danielballan** [comment]
The conda recipe with `meta.yaml` is in #187.

**Comment by nkeim** [comment]
Is the idea to ultimately have the conda stuff in master, or keep it in that branch?

**Comment by nkeim** [comment]
I updated numba versions and added a conda recipe as discussed. I also refreshed the other dependency versions used by Travis to be a little more current.

**Comment by danielballan** [comment]
Yes, the idea was to put it in master. Tagged releases should be built using a modified recipe that hard-codes the version and includes the checksum, but this recipe is intended for dev builds.

**Comment by danielballan** [comment]
This looks good to me if there are no objections to dropping numba < v0.13.4.

**Pull request merged**
