### PR TITLE
Zenodo v042

### PR DESCRIPTION
**Pull request by nkeim**
This adds the reserved Zenodo DOI for v0.4.2, and corrects a typo. It should be the last PR before the release.

I have verified that the html docs build correctly with this PR.

### CODE REVIEW

**Comment by nkeim** [comment]
Ready to merge! Then I will finish the release.

**Comment by rbnvrw** [comment]
Awesome!

I can't see the record, so just checking: can you also add me with my orcid id? It's http://orcid.org/0000-0003-3925-5732

Thanks!

**Comment by nkeim** [comment]
Hi! Sorry for the wait. That DOI is reserved (it cannot be assigned to another record), but it is not yet published. Unfortunately there is no way for me to share ownership of the record, as we learned in #570.

Once I have made a zip file with `python setup.py sdist` I can publish the DOI. Then we can check that the record is public and valid, before publishing on PyPI and conda-forge. So I think you should go ahead and merge. Thanks!

**Comment by nkeim** [comment]
BTW, in case you have not seen it yet, I am following (and revising) the [trackpy release checklist](https://github.com/soft-matter/trackpy/wiki/Release-Checklist).

**Comment by rbnvrw** [comment]
Ok, great! I've merged it.

**Comment by caspervdw** [comment]
@nkeim   I have been tracking the versioned record at Zenodo, and still haven't been able to re-enable the GH integration... I'll let you know when that is done

In the meantime, I suggest just using https://zenodo.org/badge/latestdoi/4744355 . I can make new versions under that record.

**Comment by caspervdw** [comment]
Ah @rbnvrw were almost at the same time. I don't think it is good to start adding more Zenodo records that are unrelated to the main versioned record.

To make this process much easier, I suggest only keeping the "versioned" DOI in the repo. This will be a constant. After you do the release @nkeim, just tell me then I'll make and upload new version manually to Zenodo.

I'll make a PR in a minute

**Pull request merged**
