### PR TITLE
DOC Release notes for v0.3.1

### PR DESCRIPTION
**Pull request by caspervdw**
Together with #351 this should finish release v0.3.1

### CODE REVIEW

**Comment by nkeim** [comment]
Looks great!

**Comment by caspervdw** [comment]
@danielballan @tacaswell Could one of you approve this PR and the release?

**Comment by danielballan** [comment]
Sorry for letting this go so long.

**Comment by danielballan** [comment]
Are you game to do the release? I can do conda packages as usual.

**Comment by caspervdw** [comment]
Yes I can do it now, no problem

**Comment by caspervdw** [comment]
@danielballan turns out I don't have write privileges on Pypi trackpy... can you arrange that?

**Comment by danielballan** [comment]
Done!

**Pull request merged**
