### PR TITLE
search_range docstring changed from/to integer/float

### PR DESCRIPTION
**Pull request by apiszcz**
search_range docstring changed from/to integer/float

### CODE REVIEW

**Comment by danielballan** [comment]
@nkeim please confirm that I'm right about this. I'm 99% sure, but would appreciate a confirmation before I merge this.

**Comment by danielballan** [comment]
@apiszcz There are couple other instances of this, as I mentioned off hand in #232, this occurs in a couple places in that file (`link`, `link_df`, `link_iter`). Would you mind getting them all in this PR?

**Comment by nkeim** [comment]
Yes, @apiscz is right and the original docstring is wrong. `search_range` can be and often is a float. Thanks, @apiscz !

**Comment by danielballan** [comment]
@apiszcz Can you spare a moment to update the other `link_*` docstrings in your PR?

**Comment by apiszcz** [comment]
Done.​

**Comment by tacaswell** [comment]
@apiszcz Thanks!

**Pull request merged**
