### PR TITLE
WIP Appveyor

### PR DESCRIPTION
**Pull request by caspervdw**
Still work in progress. See https://ci.appveyor.com/project/caspervdw/trackpy/ . We should switch on Appveyor for soft-matter/trackpy before merging.

### CODE REVIEW

**Comment by caspervdw** [comment]
Nose does not find any tests! Any suggestions? @apiszcz you work on Windows, right?

**Comment by nkeim** [comment]
Neat!!! It's weird that appveyor reports that trackpy is at version "1.0.3," but that seems pretty low-priority.

Agreed that slimmed-down tests are appropriate; this is most useful as a smoke test.

Thanks!!

**Comment by caspervdw** [comment]
Yes, just something I noted, Travis also skips `slow` decorated tests. We might want to change that? Travis build times are still within acceptable limits, and locally, all tests in total take only 3 minutes.

**Comment by caspervdw** [comment]
Oh wait:

```
**Ran 0 tests in 4.229s
OK
Build success**
```

**Comment by caspervdw** [comment]
@nkeim the tests run now, but the `slow` tests are not ignored. Also there is something wrong in the `test_storage` part.

**Comment by nkeim** [comment]
Interesting! In the py2.7 tests, it looks like there is an error in image subtraction that happens as data are being generated for the storage tests. Somehow subtraction is not defined for pims frames. And in the py3.6 tests, somehow matplotlib's `imread()` [is being called with an invalid keyword arg](https://ci.appveyor.com/project/caspervdw/trackpy/build/1.0.4/job/qxsyjkj1k1389ece#L917).

In the package list I notice this:

```
pims                      0.4.1                      py_1    conda-forge
PIMS                      0.4.1                     <pip>
```

Should we hold off this PR until we drop pims as a dependency?

We also get a MemoryError [in one of the 3D g(r) tests](https://ci.appveyor.com/project/caspervdw/trackpy/build/1.0.4/job/jef6sqgd9gax15ov#L716). If it's because Appveyor is very memory-constrained maybe we should just skip that test.

**Comment by caspervdw** [comment]
This passed! I couldn't wait and squashed + merged #492 + my PR to that branch. PIMS has some inconsistent behaviour with dtypes, that's why the tests failed before. 
See here: https://ci.appveyor.com/project/caspervdw/trackpy/build/1.0.18

I'll now remove the last commit.

**Comment by nkeim** [comment]
@caspervdw Is there a branch that has working appveyor and no pims? I'm not sure if that's what you were referring to. If so, it seems like we're ready to merge.

**Comment by caspervdw** [comment]
@nkeim I rebased this branch now and dropped pims from the build recipes. 
Tests should pass now!

**Comment by caspervdw** [comment]
@nkeim done! Maybe best to squash and merge this one..

**Pull request merged**
