### PR TITLE
DOC: Find_link docstrings

### PR DESCRIPTION
**Pull request by nkeim**
In reviewing #448, I found a few opportunities to make the code easier to navigate. This PR should be considered *after* merging #448.

### CODE REVIEW

**Comment by caspervdw** [comment]
@nkeim I will review this after you rebased

**Comment by nkeim** [comment]
OK @caspervdw . Sorry for not seeing this needs attention. I will do it by Saturday at the latest.

**Comment by nkeim** [comment]
Rebased and ready to merge.

**Comment by caspervdw** [comment]
Thanks @nkeim!

**Pull request merged**
