### PR TITLE
Fix for issue #734

### PR DESCRIPTION
**Pull request by kevin-duclos**
Change traj.set_index call to avoid Pandas error: 'ValueError: cannot reindex on an axis with duplicate labels'.

### CODE REVIEW

**Review by caspervdw — CHANGES_REQUESTED** [review]
Thanks for your PR @kevin-duclos. I haven't worked with pandas for a while so I am not sure why this error is happening. But looking at the code, I think it might be a fix for your specific issue, but in general, the code should work for inputs without the `"particle"` column too. This is not reflected by the unittests however (they all use inputs with the "particle" column).

Maybe @nkeim can comment on the specific intended usage of this function?

**Comment by nkeim** [comment]
Thanks @kevin-duclos . The error in #734 makes sense, except it should occur any time that there are many particles, including in the trackpy tests. So I'm confused.

I made changes to `subtract_drift()` and its docstring that I think address @caspervdw 's concern. However, at least temporarily, I added some lines to the tests that are supposed to trigger this error. We'll see if any of the CI environments catch it.

**Comment by nkeim** [comment]
OK, I think this is ready to merge. In addition to the fix by @kevin-duclos , we now include two tests with no `particle` column:
- DataFrame with only one particle. This is unlikely to cause any reindexing problem.
- DataFrame with many (unlabeled) particles. This would be the case if one tried to use `subtract_drift()` with feature data prior to tracking. Note that  `compute_drift()` requires a `particle` column, so the user would need to compute the drift some other way.

I think this is ready to merge. @caspervdw does this address your question? @kevin-duclos do you think this still fixes the bug?

**Comment by nkeim** [comment]
Just bumping this issue, especially for @kevin-duclos : Is this OK to merge?

**Review by caspervdw — APPROVED** [review]

**Comment by kevin-duclos** [comment]
All good with me, @nkeim. Thanks!

**Comment by xyc2718** [comment]
After the 0.6.2 update, the dataframe processed by **subtract_drift()** poses an issue for **imsd()** due to the presence of "particle" in both row and column indices. To address this, it needs to use **dataframe.reset_index(drop=True)** before running the function to ensure proper execution.

**Pull request merged**
