### PR TITLE
Fix VisibleDeprecationWarning

### PR DESCRIPTION
**Pull request by ivanovmg**
Fixes https://github.com/soft-matter/trackpy/issues/629

### CODE REVIEW

**Comment by tacaswell** [comment]
This seems to break on newer versions of scipy?

**Comment by ivanovmg** [comment]
> 
> 
> This seems to break on newer versions of scipy?

Actually I get the same errors in tests locally on the master branch. So, looks like the problem with the build failing is not caused by the changes introduced.

**Comment by tacaswell** [comment]
https://travis-ci.org/github/soft-matter/trackpy/builds/707634015 passed (about a month ago).

**Comment by tacaswell** [comment]
I just added a weekly cron-job to re-run master, lets see what CI has to say for its self...

**Comment by anntzer** [comment]
I can confirm this already test is broken as of master.  Actually looking at its contents it is unclear to me how it can have passed before, as it seems to check that the computed drift from a set of random walkers is *exactly* zero (it should be close to zero, certainly, but not *exactly* zero).

**Comment by caspervdw** [comment]
The VisibleDeprecation warning is now solved as part of #641. I am trying to address other test failures as well.

**Pull request closed without merging**
