### PR TITLE
BLD: Add test env representing "clean Anaconda"

### PR DESCRIPTION
**Pull request by nkeim**
This is a _possible_ way to check that the most basic installation instructions will work — that someone can simply install Anaconda and run `conda -c soft-matter install trackpy`. See https://github.com/soft-matter/pims/pull/200 and https://github.com/soft-matter/trackpy/issues/301#issuecomment-156223916

### CODE REVIEW

**Comment by caspervdw** [comment]
I think you could drop scikit-image and pillow for this test.

**Comment by danielballan** [comment]
Why not DEPS=trackpy? Probably have to refactor to add the soft-matter
channel below:

**Comment by nkeim** [comment]
`DEPS=trackpy` would decouple test results from specific commits. It could be chaos…or it could be really convenient :smile:.

Could Travis do `conda build`, install the resulting package, and then run the tests?

**Comment by tacaswell** [comment]
In principle doing the package build, installing in and then testing _should_ be possible, but you have to be careful that `nose` picks up the right version of the code.  We tried to do this for bnl code and ran into issues with the tests always picking up the source version.

**Comment by nkeim** [comment]
Good point. What about moving the tests into the package root, then deleting `trackpy`?

**Comment by nkeim** [comment]
OK, I have a working solution. The conda recipe can run nosetests automatically as part of the build, in a clean environment (this can be turned off if you're in a hurry). So one of the test scripts just runs "conda build" instead of nosetests.

The actual setup required for that is a mess. Any improvements to `.travis.yml` would be welcome. The other downside is that this build takes almost 5 minutes, instead of the usual 3. The side benefit is that testing would be baked into our conda release process, which seems like a pretty good idea.

Please forgive all the Travis emails you probably got, and the messy commit history. I'm still not 100% sold on this idea, but it would catch a whole class of particularly embarassing issues.

**Comment by danielballan** [comment]
As it happens, we're having this same conversation at work.

I'm not completely sold -- debugging this kind of thing on Travis is so painful -- but it would have caught things like the pillow 3.0.0 problem right away.

**Comment by caspervdw** [comment]
What is exactly the difference between the clean trackpy build and the older py3.5 build with the explicit dependency list?
I think the problem here is that we are a bit sloppy on the dependencies. If we would be concise on that, the old way of doing it would suffice. 
Until we do that, I'd say :+1: for this test setup. 

 But we really should discuss which dependencies we want (including for example deps-of-deps like skimage depending on pillow).

**Comment by nkeim** [comment]
@danielballan I've just learned how hard it is to debug :stuck_out_tongue_closed_eyes:. I would argue that it's not quite as bad as it seems, since the only thing that happens on Travis exclusively is building the package straight from the repo. conda is meant to make the subsequent testing as reproducible as possible.

BUT, maybe the answer is
- Don't change the structure of `travis.yml`. It was already hard enough to debug. Just add an env with no version pinning. This will still be a pretty good "early warning system" for dependency problems.
- Merge the conda recipe that includes testing. I really like this way of validating the dependency list and the built package. One more bit of QA for stable releases. Does anyone know if Binstar will also run testing in our `dev` builds? (And do we even want that?)

**Comment by danielballan** [comment]
I'm coming around this. Soon, I'd like to automatically upload conda packages of the master branch from Travis. And since we would be doing that blindly, I can see the case for running the tests on the built package. I like that all this happens in a separate build from the plain "Python 3.5 + latest version of everything" build.

Binstar won't run the tests, no. They have a "binstar build server" but it's unclear whether that project is still actively maintained. I would plan on using Travis to do our conda-building for the foreseeable future.

**Comment by danielballan** [comment]
Note: all this was superceded by the entrance of conda-forge onto the scene.

**Pull request closed without merging**
